stages:
  - release

release:
  image: python:3.6
  stage: release
  only:
    - tags
  script:
    - pip3 install gitlab-release
    - python setup.py bdist_wheel
    - gitlab-release --link-artifact dist/*.whl
  artifacts:
    paths:
    - dist/


