# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:2.7.14

pipelines:
  tags:
    '*.*.0':
      - step:
          name: Build and upload wheel
          trigger: automatic
          script: # Modify the commands below to build your repository.
            - python setup.py bdist_wheel
            - find dist -type f -exec curl "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads"
